#!/bin/sh
echo "----------Updating bzImage-----------"
cd /root/source/linux-6.7
pwd
cp -v /work-files/bootDir/.config /root/source/linux-6.7/.config
make menuconfig
cp -v /root/source/linux-6.7/.config /work-files/bootDir/.config
make -j 12
rm -v /work-files/build/bzImage
cp -v /root/source/linux-6.7/arch/x86/boot/bzImage /work-files/build/
cd /work-files
